spring.application.name=meta-builder
spring.datasource.url=jdbc:postgresql://localhost:5432/meta_builder
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# Load .env file from the root directory
spring.config.import=optional:file:.env
